const authorities = require('./authoritiesCollection');

module.exports = [{
    _id: 2282001,
    name: 'Rohan Mondal',
    semester: 2,
    password: 'RohanMondal',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282002,
    name: 'Satarupa Mukherjee',
    semester: 2,
    dept: 'MCA',
    password: 'SatarupaMukherjee',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282003,
    name: 'Somtirtha Bhowmick',
    semester: 2,
    dept: 'MCA',
    password: 'SomtirthaBhowmick',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    }
},
{
    _id: 2282004,
    name: 'Nil Nitin Mukesh',
    semester: 2,
    password: 'NilNitinMukesh',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282005,
    name: 'Soumyodeep Mondal',
    semester: 2,
    password: 'SoumyodeepMondal',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282052,
    name: 'Anuraag Karmakar',
    semester: 2,
    password: 'AnuraagKarmakar',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282007,
    name: 'Arjun Keshab Karfa',
    semester: 2,
    password: 'ArjunKarfa',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282008,
    name: 'Dhriti Kundu',
    semester: 2,
    password: 'DhritiKundu',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282049,
    name: 'Arka Samaddar',
    semester: 2,
    password: 'ArkaSamaddar',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282006,
    name: 'Indrani Dutta Gupta',
    semester: 2,
    password: 'IndraniDuttaGupta',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
},
{
    _id: 2282059,
    name: 'Atrayee Das',
    semester: 2,
    password: 'AtrayeeDas',
    subjects: {
        'MCAP1201': { ...authorities },
        'MCAP1202': { ...authorities },
        'MCAP1203': { ...authorities },
        'MCAP1204': { ...authorities },
        'MCAP1205': { ...authorities },
    },
}];