export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as MarksPortal } from './MarksPortal';
export { default as AdminMembers } from './AdminMembers';
export { default as Navbar } from './Navbar';
export { default as SemSelection } from './SemSelection';
export { default as Department } from './Department';
export { default as SubjectSelection } from './SubjectSelection';
export { default as StudentsMarks } from './StudentsMarks'